USE [master]
GO

/****** Object:  Database [Corporation]    Script Date: 28.04.2021 14:09:15 ******/
CREATE DATABASE [Corporation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Corporation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Corporation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Corporation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Corporation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Corporation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Corporation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Corporation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Corporation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Corporation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Corporation] SET ARITHABORT OFF 
GO

ALTER DATABASE [Corporation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Corporation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Corporation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Corporation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Corporation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Corporation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Corporation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Corporation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Corporation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Corporation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Corporation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Corporation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Corporation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Corporation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Corporation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Corporation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Corporation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Corporation] SET RECOVERY FULL 
GO

ALTER DATABASE [Corporation] SET  MULTI_USER 
GO

ALTER DATABASE [Corporation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Corporation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Corporation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Corporation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Corporation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Corporation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Corporation] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Corporation] SET  READ_WRITE 
GO

